# GitHub Actions CI/CD with Next.js build caching
name: CI/CD with Next.js Caching

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
          ${{ runner.os }}-nextjs-

    - name: Install dependencies
      run: npm ci

    - name: Type check
      run: npm run typecheck
      if: ${{ hashFiles('tsconfig.json') }}

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build
      env:
        # Add your environment variables here
        NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    - name: Cache build output
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.next
        key: ${{ runner.os }}-nextjs-build-${{ github.sha }}

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Restore build cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.next
        key: ${{ runner.os }}-nextjs-build-${{ github.sha }}

    # Add your deployment steps here
    # - name: Deploy to production
    #   run: echo "Deploy to production"